export const Token = {
    ASSIGN: "ASSIGN",
    BOOLEAN: "BOOLEAN",
    DOT: "DOT",
    EQUALS: "EQUALS",
    NUMBER: "NUMBER",
    STRING: "STRING",
    IDENTIFIER: "IDENTIFIER",
    OPERATOR: "OP",
    NOT: "NOT",
    NOT_EQUAL: "NOT_EQUAL",
    AND: "AND",
    OR: "OR",
    LPAREN: "LPAREN",
    RPAREN: "RPAREN",
    CONTAINS: "CONTAINS",
    IN: "IN",
    COMMA: "COMMA",
    LBRACKET: "LBRACKET",
    RBRACKET: "RBRACKET",
}; 